export const kendroDetails = [
  {
    voter_id: "470189317002",
    name: "করিমন বিবি",
    serial_no: "001",
    father_name: "সিরাজ উদ্দিন হাওঃ",
    mother_name: "ইনসান বিবি",
    occupation: "গৃহিনী",
    date_of_birth: "02/10/1932",
    address: "5/65, জি এন ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317004",
    name: "সালমা পারভীন",
    serial_no: "002",
    father_name: "আব্দুল লতিফ মোল্লা",
    mother_name: "জোসনা বেগম",
    occupation: "ছাত্র-ছাত্রী",
    date_of_birth: "07/12/1984",
    address: "5/65, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317005",
    name: "সোনিয়া পারভীন",
    serial_no: "003",
    father_name: "মোঃ আঃ লতিফ",
    mother_name: "জোসনা বেগম",
    occupation: "ছাত্রছাত্রী",
    date_of_birth: "31/05/1988",
    address: "5.65, জি এন ব্যাংক রোড, 26, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317007",
    name: "মোছাঃ শাহিদা আক্তার",
    serial_no: "004",
    father_name: "মোঃ মহত আলী মোল্লা",
    mother_name: "করিমন বিবি",
    occupation: "গৃহিনী",
    date_of_birth: "08/02/1984",
    address: "5/65, জি এন ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317009",
    name: "জোসনা বেগম",
    serial_no: "005",
    father_name: "কাছু শেখ",
    mother_name: "জাহেদা বেগম",
    occupation: "গৃহিনী",
    date_of_birth: "05/01/1969",
    address: "5/65, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317010",
    name: "পুষ্প রানী সরকার",
    serial_no: "006",
    father_name: "যোগেশ চন্দ্র সরকার",
    mother_name: "বেমালা সরকার",
    occupation: "সরকারী চাকুরী",
    date_of_birth: "28/03/1966",
    address: "63/3, জি এন বি রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317012",
    name: "লাভলী খানম",
    serial_no: "007",
    father_name: "মোঃ চাঁদ আলী মিঞা",
    mother_name: "জাহানারা বেগম",
    occupation: "গৃহিনী",
    date_of_birth: "10/10/1987",
    address: "63/3, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189397014",
    name: "নুরজাহান বেগম",
    serial_no: "008",
    father_name: "শেখ আব্দুল আজিজ",
    mother_name: "হামিদা বেগম",
    occupation: "গৃহিনী",
    date_of_birth: "25/05/1962",
    address: "নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317016",
    name: "ত্রিনয়নী দেবনাথ",
    serial_no: "009",
    father_name: "অনাথ বন্ধু দেবনাথ",
    mother_name: "শৈল বালা দেবনাথ",
    occupation: "সরকারী চাকুরী",
    date_of_birth: "02/12/1955",
    address: "66, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317017",
    name: "বনবীথি দেবনাথ",
    serial_no: "010",
    father_name: "দুলাল কৃষ্ণ দেবনাথ",
    mother_name: "ত্রিনয়নী দেবনাথ",
    occupation: "ছাত্র/ছাত্রী",
    date_of_birth: "01/03/1976",
    address: "66, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317019",
    name: "শারমীন আক্তার",
    serial_no: "011",
    father_name: "মোঃ শহিদুল ইসলাম",
    mother_name: "শাহানারা ইসলাম",
    occupation: "গৃহিনী",
    date_of_birth: "04/03/1986",
    address: "66, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317021",
    name: "আমেনা খাতুন",
    serial_no: "012",
    father_name: "আব্দুল কাদের মুন্সী",
    mother_name: "নিহারুন নেছা",
    occupation: "গৃহিনী",
    date_of_birth: "06/09/1959",
    address: "62, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317023",
    name: "নাছিমা আক্তার",
    serial_no: "013",
    father_name: "সুলতান সরদার",
    mother_name: "রাবেয়া খাতুন",
    occupation: "গৃহিনী",
    date_of_birth: "13/08/1969",
    address: "62, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317030",
    name: "খাদিজা বেগম",
    serial_no: "014",
    father_name: "আরমান সরদার",
    mother_name: "শুকুরুশ্লেষা",
    occupation: "সরকারী চাকুরী",
    date_of_birth: "01/04/1956",
    address: "64, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
  {
    voter_id: "470189317034",
    name: "সাহানা ইসলাম",
    serial_no: "015",
    father_name: "এ্যাডঃ রেজাউল করিম",
    mother_name: "সুরাইয়া করিম",
    occupation: "গৃহিনী",
    date_of_birth: "22/06/1990",
    address: "64, নর্থ খাল ব্যাংক রোড, সোনাডাঙ্গা, খুলনা",
    election_info: {
      polling_station: "বানিয়া খামার ঈদগা স্কুল",
      division: "Khulna",
      district: "Khulna",
      sub_district: "Sonadanga",
      ward_no: "26",
      voter_area_no: "0189",
      post_code: "9100",
    },
  },
];

export async function getVotars() {
  return kendroDetails;
}
